- rebar.config
- src/graphql_execute.erl
- src/graphql_schema.erl
- src/graphql_schema_parse.erl
We replace lager with the built-in error logger. It strips off the
lager dependency and we don't need that since the error logger can do
its job. Furthermore, lager will pick up the error logger messages
anyway and transform them in the system, so we don't lose anything by
doing this.
The change brings the dependencies from 1 to 0.
Reported-By: @goertzenator -- who noted that GraphQL is 0.38megabyte
in size whereas lager is close to 2megabyte.
> Remove the dependency on lager

- rebar.config
- rebar.lock
- src/graphql.app.src
lager was still part of the app.src and rebar.lock. This PR remove it. While i'm here i fixed the jsx dependency line in rebar.config to use `tag` instead of `branch`
> fix application boot: remove lager definitely

- src/graphql_execute.erl
When an error is encountered the path information seems to be in reversed order. This is the current behavior:
```
{
"data": { "node": null },
"errors": [
{
"path": [
"node",
"NodeQuery"
],
"reason": "not_found"
}
]
}
```
This patch should result in this:
```
{
"data": { "node": null },
"errors": [
{
"path": [
"NodeQuery",
"node"
],
"reason": "not_found"
}
]
}
```
> Fix the order of the path when an error is encountered

- src/graphql_ast.erl
- src/graphql_elaborate.erl
If a type name is not found, do not output the structure, but send the
failing ID along to the graph_err path. This ought to fix some
problems where an error that is client-side is incorrectly registered
as server side.
> Fix elaborator type names

- src/graphql_type_check.erl
- test/dungeon_SUITE.erl
The variant where your query has a single operation with parameters
was not handled correctly. It was rejected, but the spec says it
should be accepted.
The problem is in the type checking phase for parameters. It didn't
account for this particular case correctly, so you obtained the empty
map as the parameters list. This of course breaks deep down in the
execution code since it assumes all parameters have been correctly
checked.
The fix is to analyze the environment and if there is a single
operation, with no "OpName" given, then assume it is *the* operation
to execute.
It also makes @lozhuf happy :)
> Fix GetOperation for parameterized operation calls

- src/graphql_schema_validate.erl
If the schema validation fails, we can handle it nicer by reporting
the error specifically. We catch the most common one for now and then
we can add more error reporters later on in the schema validator.
> Add code which improves error reporting on schema validation

- src/graphql_execute.erl
- test/dungeon_SUITE.erl
- test/dungeon_SUITE_data/dungeon_schema.graphql
- test/dungeon_monster.erl
If the Schema expects a float but you have an integer, we convert the
integer to a float and use that instead as the output. There are some
caveats to doing this, but I think we are better served by doing it.
* Floating points can only represent certain integers precisely.
Otherwise they become approximate. But since the context is a float
anyway, there is no loss of precision client-wise.
* Erlang systems can at times produce integers in FP contexts because
the language is dynamically typed and you write with "numbers" in
some situations.
* The danger of doing this is that there may be situations in which
the programmer never intended an integer but gets one anyway. You
can assert this in your own executor if you need this functionality.
Alternatively, you can create your own scalar and …
> Allow integers in floating point context. Closes #50

- src/graphql.erl
the ` json()` returned by `graphql:execute/1` has a `errors` `atom()` key that carries a list(maps) as values.
The definition will be:
```erlang
type json() :: number() | binary() | true | false | null | #{ binary() | atom() => json() } | [json()] .
```
> Add [json] to graphql:json() type definition

- src/graphql_execute.erl
- src/graphql_type_check.erl
- test/dungeon.erl
- test/dungeon_SUITE.erl
- test/dungeon_SUITE_data/dungeon.graphql
- test/dungeon_monster.erl
- test/dungeon_query.erl
- test/dungeon_room.erl
- test/dungeon_type.erl
- test/graphql_SUITE.erl
In some cases it is convenient to pass auxiliary data with the result; data that should not go directly to the end-user but should trigger some side-effect in the transport before sending data/error to the response body. This has been solved by using message passing and collect these just before we complete the top-level.
In resolvers one can, besides the two-ok-tuple (which has the old behaviour), return a three-ok-tuple which behave like this:
```
{ok, any(), [term()]}
```
The response map will now contain an `aux`-field which contain a list of terms, which can be used to modify the response object, such as a Cowboy response object, and set a cookie, add a header, etc.
N.B.: Errors cannot set auxiliary data, and one should not rely on the order in the auxiliary data list.
In this pull …
> Add support for auxiliary data in responses

- src/graphql_enum_coerce.erl
- src/graphql_execute.erl
- src/graphql_scalar_binary_coerce.erl
- src/graphql_scalar_bool_coerce.erl
- src/graphql_scalar_float_coerce.erl
- src/graphql_scalar_integer_coerce.erl
- src/graphql_schema.hrl
- src/graphql_schema_canonicalize.erl
- src/graphql_schema_parse.erl
- src/graphql_type_check.erl
This PR is related with ![](https://github.trello.services/images/mini-trello-icon.png) [GraphQL: Merge Enum and Scalar coercion into one](https://trello.com/c/QFjQMTAD/805-graphql-merge-enum-and-scalar-coercion-into-one-rid-ourselves-of-builtin-scalarst) task
Also I deleted the `input_coerce` & `output_coerce` fields and I replace that with `resolve_module` to work in the same way as the others default entities on the graph
> Merge Enum and Scalar coercion into one.

- src/graphql.erl
- src/graphql_execute.erl
- test/dungeon_monster.erl
- test/dungeon_stats.erl
This PR constructs a variant of concurrent execution relying on a closure based model.
Whenever we have an operation which is deferred, we wrap the remainder of the computation (i.e., its continuation) into a closure and return the closure. Later, when data arrives for the closure, we invoke it to compute that part of the query. This has a two outcomes:
* The closure completes. We forward the result of the computation to the *upstream* closure which is waiting for a result. If completion like this completes the top level closure, the computation is done.
* The closure returns a new closure and a list of new sub-closures generated. In this case, more data is needed for a full completion and we recurse.
While this is going on, maintain a map of the closures which are currently ongoing. …
> Make the closure core compile

- src/graphql_execute.erl
The `#work{}` structure is a far better way. In the future it also lets us propagate monitor/cancellation/timeout sets properly.
> Remove the use of the {more, _} tuple

- src/graphql_execute.erl
- test/dungeon_monster.erl
Result track whom they want to cancel. Invoke cancellation at the
defer_loop, and recurse through parts of the query which needs to be
cancelled out. If a cancelled reference is already complete, ignore it.
> Implement cancellation

- include/graphql.hrl
- src/graphql_execute.erl
- test/star_wars.erl
Allow to return `{ok, []}` [in the same way we are returning `{ok, null}`](https://github.com/shopgun/graphql-erlang/compare/dc/not-found/empty.list?expand=1#diff-53b775494385f03a4e036c2c90a6402dR732) at execute callback and make this return more explicit using  `?RETURN_NULL` and `?RETURN_EMPTY_LIST` macros
**execute/4 example**
```erlang
execute(Ctx, Cur, <<"planningSuggestions">>, Args) ->
{ok, []}; %% it will be replaced with ?RETURN_EMPTY_LIST;
..
.
```
**output:**
```json
{
"data": {
"planningSuggestions": []
}
}
```
> Allow to return [] from execute callback as valid object val

- src/graphql_type_check.erl
- test/dungeon.erl
- test/dungeon_SUITE.erl
- test/dungeon_enum.erl
- test/dungeon_mutation.erl
- test/dungeon_query.erl
Change the dungeon such that every enumeration is an atom internally.
Observe that parameter-passed values do not enjoy being fed through
the enumeration module resolver. This is obviously a problem which
needs some addressing. In this patch, we currently detect the problem,
but we don't provide a fix yet.
> Handle coercion of default values

- CHANGELOG.md
- src/graphql_ast.erl
- src/graphql_builtins.erl
- src/graphql_elaborate.erl
- src/graphql_introspection.erl
- src/graphql_parser.yrl
- src/graphql_schema.hrl
- src/graphql_type_check.erl
- test/schema_pet.erl
- test/validation_SUITE.erl
Target simpler validations, which are easy to pluck right away. Use these to solve some of the simpler issues in the repository.
> Provide validations which are low-hanging fruits

- CHANGELOG.md
- src/graphql_err.erl
- src/graphql_schema.erl
- src/graphql_type_check.erl
- test/validation_SUITE.erl
If we do this validation correctly, 4 other issues are solved right away. This PR tracks the implementation.
Preliminary plan:
> Implement validation 5.4.2.3

- CHANGELOG.md
- src/graphql_execute.erl
- test/dungeon_SUITE.erl
This solves a number of mistakes in the code base w.r.t error
handling. Rather than completing nulls at the top-level too much,
complete nulls at the point where the error occurs.
> Pass on null values rather than errors. Closes #128

- CHANGELOG.md
- src/graphql_internal.hrl
- src/graphql_parser.yrl
- src/graphql_schema_parse.erl
- test/dungeon_SUITE_data/dungeon_schema.graphql
This patch should fix the problem that you cannot attach descriptions to enum values in the schema parser.
> Address the problem of annotating enum values

- src/graphql_elaborate.erl
- src/graphql_parser.yrl
- src/graphql_schema_parse.erl
Instead of performing a schema lookup in the YRL grammar when encountering a scalar value we will replace it with a `{scalar, Name}` and perform the lookup in the parser and elaborator.
I don't know if I've done this correctly. The note about the suggested fix stated that I should only perform the lookup in the `graphql_elaborate`-module, but I had to handle the scalar-type in `graphql_schema_parse` as well it seems.
The test suite still passes when these changes are applied.
This PR is part of solving issue #91
> Remove the schema lookup from the YRL grammar

- src/graphql_type_check.erl
This format change solve this format error when the op es is not a string, for example `null` or another atom().
```erlang
{[{reason,badarg},{mfa,{server_cowboy_handler,from_json,2}},{stacktrace,[{erlang,iolist_to_binary,[["Expected an operation ",null," but no such operation was found"]],[]},{graphql_err,mk,3,[{file,"/build/jenkins/workspace/server/_build/default/lib/graphql/src/graphql_err.erl"},{line,22}]},{graphql_err,abort,3,[{file,"/build/jenkins/workspace/server/_build/default/lib/graphql/src/graphql_err.erl"},{line,16}]},{server_cowboy_handler,run,5,[{file,"/build/jenkins/workspace/server/_build/prod/lib/server_http/src/server_cowboy_handler.erl"},{line,174}]},{cowboy_rest,call,3,[{file,"/build/jenkins/workspace/server/_build/default/lib/cowboy/src/cowboy_rest.erl"},{line,976}]},{c …
```
> Format string error for Operation value

- src/graphql_builtins.erl
* prevents encoding issues mentioned in #136
> use utf8 description strings in src/graphql_builtins.erl

- src/graphql_err.erl
It is possible to hit a path component 'undefined' in the case where
no operation is given. This then leads to a path resolver error which
then fails to produce a correct error message.
> Handle undefined operations. Closes #142.

- Makefile
- test/dungeon_SUITE.erl
- test/dungeon_SUITE_data/introspection_with_variable.graphql
- test/test.spec
This PR is a **failing test** case, (_no fix included_) that demonstrates an error I came across when sending an introspection query using a variable and using that variable in a fragment.
The background is that I was trying out an [Elm GraphQl package](http://package.elm-lang.org/packages/dillonkearns/graphqelm/latest) together with your [tutorial server](https://shopgun.github.io/graphql-erlang-tutorial/) and getting this error:
```
$ graphqelm http://localhost:17290
{ errors: 
[ { message: '{error,#{key =>\n            {input_coercion,<<"Bool">>,\n                             {var,{name,19,<<"includeDeprecated">>}},\n                             not_bool},\n         message =>\n             <<"General uncategorized error: {input_coercion,<<\\"Bool\\">>,\\n …
```
> This is a failing test case covering an introspection query erro when using a variable in fragment

- CHANGELOG.md
- src/graphql_err.erl
- src/graphql_execute.erl
- src/graphql_schema.erl
- src/graphql_type_check.erl
- test/dungeon_SUITE.erl
- test/dungeon_SUITE_data/dungeon_schema.graphql
- test/dungeon_enum.erl
- test/graphql_SUITE_data/test_schema.spec
Fixes issue #156 "duplicate enum values don't work"
- enum table now stores set of enum type ids instead of just one
- dropped integer value from enum table because it wasn't used anywhere
- lookup_enum_type() removed because it may resolve to more than one type
- replaced with validate_enum()
- update enum error message to deal with multiple matches
> Permit enum value dups

- CHANGELOG.md
- src/graphql_scanner.xrl
- test/graphql_SUITE_data/test_schema.spec
This follows the Jun2018 specification rather than our own specification.
> Fix #164 - Alter block strings to use """ over `

- src/graphql_schema.hrl
- src/graphql_schema_validate.erl
- test/graphql_SUITE.erl
- test/graphql_SUITE_data/empty_union.spec
- test/graphql_SUITE_data/non_unique_union.spec
; Test empty unions. These were already correctly rejected by the
parser which disallows an empty union specification altogether. It
requires at least one entry.
; Test unions with duplicate names. This is now handled in the Schema
validator where we check a union for unique references. This ensures
a union is not going to contain the same name twice.
> Add tests for unions

- CHANGELOG.md
- src/graphql.erl
- src/graphql_execute.erl
- src/graphql_internal.hrl
- src/graphql_parser.yrl
- src/graphql_scanner.xrl
- src/graphql_schema.erl
- src/graphql_schema.hrl
- src/graphql_schema_canonicalize.erl
- src/graphql_schema_parse.erl
- src/graphql_schema_validate.erl
- test/dungeon.erl
- test/dungeon_SUITE_data/dungeon_schema.graphql
- test/graphql_SUITE_data/test_schema.spec
This pull request handles the new type system definition language. The work is going to be split over several changes:
* Alter the grammar and scanner to accept the new token types.
* Alter the injection code to handle the new format.
* Change all the specifications in tests to follow the new format.
* Go over the README.md file, and be quite aggresive with deletion as most information is in the tutorial.
* Rewrite the tutorial to follow the new format.
* Probably look into upgrading to Cowboy 2.0 in the tutorial as well.
> Type System Definition Language

- src/graphql_execute.erl
- src/graphql_introspection.erl
- src/graphql_schema.hrl
- src/graphql_schema_canonicalize.erl
I was about to do directive introspection, but found this instead.
Seemed like a resolver with arity 3 was only ever used when a field's resolve is set.
This seems to mostly be a feature useful in the instrospection where you'd like to
overwrite a field resolver instead of using the resolve module on the object.
The blog example also inlines field resolvers, which makes sense for small applications.
However, it seemed like a convenience thing that should be handled in canonicalization
so I patched that so that a field resolver always has arity 4 in the execution.
- - -
I'd also like to unify the way the resolver is specified on objects and fields.
It's a bit weird that an object takes a `resolve_module` which must be a module,
and a field takes a `resolve` which must be a function.
Naming …
> Handle field resolver arity=3 in the canonicalization instead of in the execution

- src/graphql_execute.erl
- src/graphql_schema.hrl
- src/graphql_schema_canonicalize.erl
- test/dungeon_SUITE_data/dungeon_schema.graphql
- test/graphql_SUITE_data/test_schema.spec
We didn't actually store argument definition directives anywhere.
So I added a `directives` field to the `#schema_arg{}` record and store the directives there.
I also cleaned up some type info in graphql_schema.hrl. Most records had
```erl
directives :: [directive_type()]
```
which isn't correct, it should just be a list of `graphql:directive()`
After that, dialyzer found that `format_directives/1` never actually get's `directive_type()`
which makes sense, so I removed some unused code.
I also patched up the tests to make sure argument definition directives parse and validate.
> Adding directives to argument definitions
